### PR TITLE
Move the utils into the repo phala-blockchain

### PR DESCRIPTION
**Pull request by kvinwang**
And published at https://crates.io/crates/pink-utils.
Not sure if we should put it into the pink-web3.

### CODE REVIEW

**Comment by h4x3rotab** [comment]
It's good to have a dedicated crate for attestation. However, since it's really a small feature, maybe we should put some future helper features to a `pink-utils` crate.

**Review by h4x3rotab — APPROVED** [review]
LGTM

**Comment by kvinwang** [comment]
It's in pink-utils now.

**Review by h4x3rotab — APPROVED** [review]
LGTM

**Pull request merged**
